apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logoutput
  name: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
      - image: arbilgin/log_output:1.1
        name: log-output